data = [
    ("The Aam Aadmi Party (AAP) continues to intrigue its supporters and opponents alike, but one aspect that has now become predictable about its leader Arvind Kejriwal is his infinite capacity to create a spectacle. In the latest development, Mr. Kejriwal has resigned from the post of Delhi Chief Minister, choosing AAP Minister Atishi as his replacement. Ms. Atishi has been handling a heavy basket of portfolios during Mr. Kejriwal’s long imprisonment on corruption charges. Mr. Kejriwal remained the Chief Minister during his incarceration, setting a new precedent and reinforcing his aura of defiance, but resigned after securing bail from the Supreme Court. Mr. Kejriwal had been cornered by central agencies on the grounds of investigating corruption — conduct that the Court has frowned upon. With his sudden move, and at a time of his choosing, Mr. Kejriwal is now trying to reset the course of politics in Delhi and beyond, and turn the tables on the Bharatiya Janata Party (BJP). In Delhi, the BJP has swept the last three Lok Sabha elections while AAP has won nearly all seats in two Assembly elections, indicating an overlapping political base that swings between the two parties. AAP has metamorphosed into a political party from being an anti-corruption campaign, and the BJP hopes to slow it down in the election, on grounds of its involvement in a serious corruption case.","Politics"),
    ("Asking people to cast their votes wisely in the ongoing Assembly polls that are linked to the future of Jammu and Kashmir, Prime Minister Narendra Modi said on Thursday (September 19, 2024) that they should ensure the political sunset of the Congress, National Conference (NC) and Peoples Democratic Party (PDP), which have inflicted wounds in the region for years together.","Politics"),
    ("Andhra Pradesh Chief Minister N Chandrababu Naidu has accused the previous YSRCP government of using substandard ingredients, including animal fat, in the preparation of the famed Tirupati laddoos, a sacred sweet offered at the Sri Venkateswara temple in Tirupati.","Politics"),
    ("Ravichandran Ashwin notched up his 6th Test century as he along with Ravindra Jadeja dug India out of a hole against Bangladesh in the 1st day of the 1st Test in Chennai on Thursday.","Sports"),
    ("Versatile Jugraj Singh, son of a porter at Attari-Wagah border, and India’s hero in Asian Champions Trophy hockey final","Sports"),
    ("Bangladesh dealt early blows to India in the first Test on Thursday in Chennai as the visitors claimed three wickets in the first session.24-year-old pace sensation Hasan Mahmud produced a fine opening spell as he snapped Indian captain Rohit Sharma (6), Shubman Gill (0), and Virat Kohli (6) in the first session.","Sports"),
    ("The Indian chess team is taking on Iran in the 8th round of the ongoing Chess Olympiad in Budapest, while the Indian women’s chess team will face Poland.","Sports"),
    ("33-year-old Rajasthan Administrative Service officer dies after ‘botched’ surgery, inquiry ordered","Health"),
    ("Chess Olympiad 2024 Round 7 Highlights: Gukesh defeats Wei Yi to hand India victory; Vantika Agrawal, Vaishali help women’s team win","Sports"),
    ("Crocodile vs Python, Andhra Pradesh patient watching Jr NTR movie during brain surgery, and more: Viral videos today","Health"),
    ("Despite being Rao Inderjit Singh’s daughter, I did not get a ticket for 10 years… I am here to work’: Arti Singh Rao","Politics"),
    ("AAP plugs its Dalit gap with new minister designate, Mukesh Kumar Ahlawat","Politics"),
    ("Singed by R G Kar row, TMC looks to turn a corner; BJP, CPM play waiting game","Politics"),
    ("New Karnataka govt-Governor flashpoint: Siddaramaiah moves to curb Gehlot’s power to appoint V-Cs","Politics"),
    ("In poll season, a video captures J&K job distress: ‘Seen that PhD scholar selling fruits?’","Politics"),
    ("Jamaat factor at play as villages that once heeded boycott call queue up to vote in Jammu and Kashmir","Politics"),
    ("Today in Politics: PM Modi to address two rallies in J&K; Nadda to release BJP manifesto for Haryana","Politics"),
    ("Despite ‘left in cold by all’, Kashmiri Pandits make a beeline to vote in J&K Phase 1 polls","Politics"),
    ("One Nation, One Election: BJP sends message of resolve, willing to build consensus","Politics"),
    ("One Nation, One Election: How the numbers stand in new Parliament","Politics"),
    ("Decode Politics: Rethink on new districts, why BJP Rajasthan govt will look before it leaps","Politics"),
    ("Roadmap for ‘One Nation, One Election’: If date 2029, 17 states to have Assemblies for less than 3 years","Politics"),
    ("Jamaat confirms talking to Delhi, says poll move has the mandate of its core group, the public","Politics"),
    ("As J&K heads to polling booths, where does Article 370 stand for parties","Politics"),
    ("In Valley seats, Sikh faces flag ‘govt raw deal’, pitch for jobs, Punjabi recognition","Politics"),
    ("As south states explore a federalism front against Modi govt, how history is repeating itself","Politics"),
    ("As Madhya Pradesh BJP factional feuds spill into the open, state leadership moves to contain fallout","Politics"),
    ("Global oil prices still volatile, OMCs to wait more before petrol, diesel price cut, reverting to routine fuel price revisions","Business"),
    ("Sensex ends at record high of 83,184.8, Nifty closes above 25,400 post US Fed’s 50 bps rate cut","Business"),
    ("Red Sea Crisis: Shipping Corp called into action as exports take a hit","Business"),
    ("US Fed cuts rate by 50bps: What it signals, and its impact","Business"),
    ("Maharashtra govt cancels Rs 3,000 crore insurance contract with UII","Business"),
    ("Mines ministry to set up project monitoring unit for faster mine operationalization","Business"),
    ("Federal Reserve cuts key rate by sizable half-point, signaling end to its inflation fight","Business"),
    ("Is India ready for American protectionism under Donald Trump?","Business"),
    ("Sensex, Nifty hit fresh record high levels","Business"),
    ("GST structure — the complications and the way ahead","Business"),
    ("Oppositions are attacking the ruling party and are grounding them for GST rule","Politics"),
    ("Indian oil PSUs’ dividends stuck in Russia swell to around $900 million as repatriation efforts flounder","Business"),
    ("Slowing petroleum exports drive India’s goods export lower by 9% in August; trade deficit widens to 10-month high of $30 billion","Business"),
    ("The Government increased petrol prices and has nothing to say on the increasing prices","Politics"),
    ("Exports to Bangladesh slip 28% in Aug; Crisil flags risk to export-oriented units","Business"),
    ("Steady growth in west, south states; decline in Bengal: EAC-PM report","Business"),
    ("Triptii Dimri’s relatives declared ‘no one will marry her’ because she’s an actor, said ‘mean things’ to her parents","Entertainment"),
    ("Alia Bhatt opens up about life after Raha, says raising a child has filled her with ‘fear and nerves’: ‘Haven’t had a therapy session in two months’","Entertainment"),
    ("Krushna Abhishek reacts to aunt Sunita Ahuja’s statement that even God can’t make them reconcile: ‘I love her a lot’","Entertainment"),
    ("Lokesh Kanagaraj disappointed over leaked Nagarjuna scene from Coolie: ‘Two months of hard work gone in vain’","Entertainment"),
    ("Karan Johar predicted Alia Bhatt-Ranbir Kapoor ‘would last a lifetime’ the moment he sensed sparks: ‘I knew it’","Entertainment"),
    ("D52 title out: Dhanush to direct and star in Idli Kadai","Entertainment"),
    ("Vivek Oberoi reacts to high entourage cost in Bollywood: ‘If I have to upgrade my hotel room, I pay myself’","Entertainment"),
    ("Zayed Khan answers if his net worth is Rs 1500 cr, explains how he secured himself financially amid Bollywood’s ups and downs: ‘If you can afford a Ferrari…’","Entertainment"),
    ("Sector 36 real story: Real-life Chumki Ghosh whose case led the cops to Nithari killings accused Surinder Koli, Moninder Singh Pandher","Entertainment"),
    ("Iulia Vantur, Farah Khan, Ramesh Taurani attend Himesh Reshammiya’s father Vipin Reshammiya’s last rites. Watch","Entertainment"),
    ("IC 814 survivor recalls hijackers collected donations worth Rs 80,000 for ‘poor Afghans’, a man from Karol Bagh offered to print pamphlets for their cause","Entertainment"),
    ("Amitabh Bachchan apologises for mispronouncing ‘kachra’ in Marathi, fans say ‘Sir, don’t be sorry’. Watch","Entertainment"),
    ("Suriya’s Kanguva postponed to November 14, to avert clash with Rajinikanth’s Vettaiyan","Entertainment"),
    ("Amitabh Bachchan-Jaya Bachchan’s wedding priest protested against their inter-caste marriage: ‘The whole affair was kept secret’","Entertainment"),
    ("Cannes-winner All We Imagine As Light to release in Kerala on September 21","Entertainment"),
    ("Hiphop Tamizha Adhi on ‘Kadaisi Ulaga Por’: ‘I write high moments for the film, not for the actors’","Entertainment"),
    ("Abhishek Bachchan buys a luxury apartment in Mumbai two months after buying 6 flats in Borivali: report","Entertainment"),
    ("‘Raj Kapoor’s daughter Reema was engaged to Rajendra Kumar’s son Kumar Gaurav, he left her Nargis’ daughter Namrata,’ claims Vijayta Pandit","Entertainment"),
    ("Inside Shabana Azmi’s 74th birthday party: Vidya Balan, Urmila Matondkar, Dia Mirza attend; 3-tier cake celebrates her 50 years in cinema","Entertainment"),
    ("Aaradhya Bachchan runs to hug mom Aishwarya Rai upon her SIIMA win, touches Kannada superstar Shiva Rajkumar’s feet, fans call her ‘Sanskari","Entertainment"),
    ("Aamir Khan experimented with drinking for Raja Hindustani song; wasn’t happy with it: Archana Puran Singh","Entertainment"),
    ("‘Shah Rukh Khan, come and help my son,’ requests Vijayta Pandit as she recalls his promise to late husband Aadesh Shrivastava on his death bed","Entertainment"),
    ("Arijit Singh calls stage his temple as he removes food container placed by fan on stage at London concert: ‘You can’t food put here’","Entertainment"),
    ("Kirron Kher reveals she continued to judge India’s Got Talent during cancer treatment: ‘First few months were very tough’","Entertainment"),
    ("Saiee Manjrekar says 37-year age gap with Salman Khan in Dabangg 3 didn’t affect her: ‘I was oblivious to that discussion’","Entertainment"),
    ("When teenage Virat Kohli played a Ranji Trophy match hours after his father's demise","Sports"),
    ("Shaqkere Parris hits jaw-dropping 124m six in CPL clash","Sports"),
    ("AITA slammed Sumit Nagal for refusing to play in India's recent Davis Cup tie vs Sweden, and revealed his annual fee demand.","Sports"),
    ("Alyssa Healy on Australia’s dominion over world cricket: ‘We are being hunted at every opportunity’","Sports"),
    ("Salvatore ‘Totò’ Schillaci, top scorer of the 1990 FIFA World Cup, dies at 59","Sports"),
    ("Inter Milan hold Man City to surprise 0-0 draw in Champions League opener","Sports"),
    ("Versatile Jugraj Singh, son of a porter at Attari-Wagah border, and India’s hero in Asian Champions Trophy hockey final","Sports"),
    ("India vs Bangladesh Live Score, 1st Test Day 1: IND 339/6, R Ashwin and R Jadeja remain unbeaten at stumps in Chennai","Sports"),
    ("After the flood, Gujarat BJP tries to climb out of deep waters, lends help on damaged cars","Politics"),
    ("‘Planned flood’: As south Bengal is inundated, Mamata Banerjee threatens to snap ties with DVC","Politics"),
    ("Eye on Bihar polls, NDA mounts damage control over Mahadalit home burning as INDIA raises storm","Politics"),
    ("Early red card hampers Barcelona in Champions League loss to Monaco","Sports"),
    ("New Karnataka govt-Governor flashpoint: Siddaramaiah moves to curb Gehlot’s power to appoint V-Cs","Politics"),
    ("Jamaat factor at play as villages that once heeded boycott call queue up to vote in Jammu and Kashmir","Politics"),
    ("Despite left in cold by all, Kashmiri Pandits make a beeline to vote in J&K Phase 1 polls","Politics"),
    ("US Fed cuts rate by 50bps: What it signals, and its impact","Business"),
    ("A less-complex GST structure essentially would imply a reduction in the number of tax slabs, minimal carve outs and exemptions, easier compliance mechanism and rates at a level at which both states and the Centre are able to safeguard their revenue streams.","Business"),
    ("The issue has also featured in government-to-government discussions between New Delhi and Moscow, but a resolution is still awaited due to various complications arising from Western sanctions on Moscow and its energy sector.","Business"),
    ("Samsung sues Indian labour union over strike as dispute escalates","Business"),
    
    

    ]